"""
Network structure radar charts by cluster (multi-scenario per chart).
Uses official scenario naming consistent with other visualizations.
"""
from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path
from typing import Dict, List

import numpy as np
import matplotlib.pyplot as plt

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent

# Metrics CSV generated by network classification step
DEFAULT_METRICS_CSV = PROJECT_ROOT / (
    "products/supply_chain_optimization/visualization/results/"
    "network_classification_20260127_210416/scenario_network_metrics.csv"
)

# Official scenario codes used across visualization scripts
SCENARIO_NAME_MAP: Dict[str, str] = {
    "Coal Hydrogen": "CTL",
    "Byproduct H2 + Coal": "CTL-BH",

    "Natural Gas Two-Step": "GTL-GH-MTJ",
    "Natural Gas One-Step": "GTL-GH-FT",
    "Byproduct H2 + NG Two-Step": "GTL-BH-MTJ",

    "DAC Two-Step": "DAC-GH-MTJ",
    "DAC One-Step": "DAC-GH-FT",

    "Green H2 Two-Step": "CCU-GH-MTJ",
    "Green H2 One-Step": "CCU-GH-FT",

    "Byproduct H2 Two-Step": "CCU-BH-MTJ",
    "Byproduct H2 One-Step": "CCU-BH-FT",

    "Byproduct H2 + DAC Two-Step": "DAC-BH-MTJ",
    "Byproduct H2 + DAC One-Step": "DAC-BH-FT",
}

AXIS_LABELS = [
    "Node Count",
    "Top 10% Node Flow Share",
    "Top 3 Route Flow Share",
    "Avg Transport Distance (km)",
    "Cross-Region Logistics Share (%)",
    "Single-Point Failure Impact (%)",
]


def _load_metrics(csv_path: Path):
    rows = []
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    if not rows:
        raise ValueError(f"No data in metrics file: {csv_path}")
    return rows


def _normalize_metrics(metrics: np.ndarray) -> np.ndarray:
    mins = metrics.min(axis=0)
    maxs = metrics.max(axis=0)
    span = np.where((maxs - mins) == 0, 1.0, (maxs - mins))
    return (metrics - mins) / span


def main(metrics_csv: Path = DEFAULT_METRICS_CSV) -> Path:
    rows = _load_metrics(metrics_csv)

    scenarios = [r["Scenario"] for r in rows]
    display_names = [SCENARIO_NAME_MAP.get(s, s) for s in scenarios]
    clusters = [int(r["Cluster"]) for r in rows]

    metrics = np.array([
        [
            float(r["节点数量"]),
            float(r["关键节点集中度"]),
            float(r["关键通道集中度"]),
            float(r["平均运输距离"]),
            float(r["跨区域物流比例"]),
            float(r["单点失效影响"]),
        ]
        for r in rows
    ], dtype=float)

    metrics_n = _normalize_metrics(metrics)

    angles = np.linspace(0, 2 * np.pi, len(AXIS_LABELS), endpoint=False).tolist()
    angles += angles[:1]

    out_dir = PROJECT_ROOT / (
        "products/supply_chain_optimization/visualization/results/"
        f"network_radar_clusters_multi_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    cluster_map: Dict[int, List[int]] = {}
    for idx, c in enumerate(clusters):
        cluster_map.setdefault(c, []).append(idx)

    for c, idxs in sorted(cluster_map.items()):
        fig = plt.figure(figsize=(7.2, 7.2))
        ax = plt.subplot(111, polar=True)
        colors = plt.cm.tab10.colors

        for j, i in enumerate(idxs):
            vals = metrics_n[i].tolist()
            vals += vals[:1]
            color = colors[j % len(colors)]
            ax.plot(angles, vals, linewidth=1.8, label=display_names[i], color=color)

        ax.set_thetagrids(np.degrees(angles[:-1]), AXIS_LABELS, fontsize=9)
        ax.set_ylim(0, 1)
        ax.set_title(f"Cluster {c} Scenarios", pad=14)
        ax.legend(loc="upper right", bbox_to_anchor=(1.25, 1.1), fontsize=8, frameon=False)

        out_path = out_dir / f"cluster_{c}_scenarios_radar.png"
        fig.savefig(out_path, dpi=300, bbox_inches="tight")
        plt.close(fig)

    # Save a renamed CSV for reference
    renamed_csv = out_dir / "scenario_network_metrics_official_names.csv"
    with renamed_csv.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "Scenario",
            *["节点数量", "关键节点集中度", "关键通道集中度", "平均运输距离", "跨区域物流比例", "单点失效影响"],
            "Cluster",
            "TransportSummary",
            "OfficialName",
        ])
        for r, name in zip(rows, display_names):
            writer.writerow([
                r["Scenario"],
                r["节点数量"],
                r["关键节点集中度"],
                r["关键通道集中度"],
                r["平均运输距离"],
                r["跨区域物流比例"],
                r["单点失效影响"],
                r["Cluster"],
                r.get("TransportSummary", ""),
                name,
            ])

    print(f"Saved radar charts to: {out_dir}")
    return out_dir


if __name__ == "__main__":
    main()
