"""
Utilities for translating coal procurement assumptions into CO₂ supply and cost
signals for the coal-based SAF optimizer.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Mapping, Optional


@dataclass(frozen=True)
class CoalCostBreakdown:
    """Structured representation of cost results returned by the manager."""

    purchase_cost: float
    gasification_cost: float

    @property
    def total_cost(self) -> float:
        return self.purchase_cost + self.gasification_cost


class CoalSupplyManager:
    """
    Encapsulates coal-to-CO₂ yield and cost calculations for the coal SAF route.

    Parameters
    ----------
    config:
        Mapping that must contain a ``coal_parameters`` section with the keys
        documented below.

    Required configuration keys
    ---------------------------
    ``coal_parameters``:
        - ``coal_type``: Descriptive label (string).
        - ``carbon_content``: Mass fraction of carbon in the coal feedstock.
        - ``co2_per_kg_coal``: CO₂ yield per kilogram of coal (kg/kg).
        - ``coal_price_yuan_per_ton``: Procurement price (yuan/ton).
        - ``gasification_efficiency``: Thermochemical efficiency (fraction).
        - ``gasification_energy_mj_per_kg``: Energy required for gasification.
        - ``gasification_energy_cost_yuan_per_mj``: Energy cost coefficient.
        - ``coal_consumption_kg_per_kg_saf``: Coal required per kg of SAF.
        - ``base_co2_yield_kg_per_kg_saf``: CO₂ required per kg of SAF.
    """

    REQUIRED_FIELDS = {
        "coal_type",
        "carbon_content",
        "co2_per_kg_coal",
        "coal_price_yuan_per_ton",
        "gasification_efficiency",
        "gasification_energy_mj_per_kg",
        "gasification_energy_cost_yuan_per_mj",
        "coal_consumption_kg_per_kg_saf",
    }

    def __init__(self, config: Mapping[str, Any]) -> None:
        if "coal_parameters" not in config:
            raise KeyError("Configuration missing 'coal_parameters' section.")

        coal_cfg = dict(config["coal_parameters"])
        missing = [field for field in self.REQUIRED_FIELDS if field not in coal_cfg]
        if missing:
            raise KeyError(f"Missing coal parameters: {', '.join(sorted(missing))}")

        self._params = coal_cfg
        self.coal_type: str = coal_cfg["coal_type"]
        self.carbon_content: float = float(coal_cfg["carbon_content"])
        self.co2_per_kg_coal: float = float(coal_cfg["co2_per_kg_coal"])
        self.coal_price_yuan_per_ton: float = float(
            coal_cfg["coal_price_yuan_per_ton"]
        )
        self.gasification_efficiency: float = float(
            coal_cfg["gasification_efficiency"]
        )
        self.gasification_energy_mj_per_kg: float = float(
            coal_cfg["gasification_energy_mj_per_kg"]
        )
        self.gasification_energy_cost_yuan_per_mj: float = float(
            coal_cfg["gasification_energy_cost_yuan_per_mj"]
        )
        self.coal_consumption_kg_per_kg_saf: float = float(
            coal_cfg["coal_consumption_kg_per_kg_saf"]
        )
        self.base_co2_yield_kg_per_kg_saf: float = float(
            coal_cfg.get(
                "base_co2_yield_kg_per_kg_saf",
                self.coal_consumption_kg_per_kg_saf * self.co2_per_kg_coal,
            )
        )

        self.coal_price_yuan_per_kg: float = self.coal_price_yuan_per_ton / 1000.0

    def _validate_mass(self, value: Any, name: str) -> float:
        try:
            mass_value = float(value)
        except (TypeError, ValueError) as exc:  # pragma: no cover - defensive
            raise TypeError(f"{name} must be a numeric value.") from exc

        if mass_value < 0:
            raise ValueError(f"{name} must be non-negative.")
        return mass_value

    def calculate_co2_from_coal(self, coal_kg: Any) -> float:
        """Return CO₂ output (kg) generated by the supplied coal mass."""
        coal_mass = self._validate_mass(coal_kg, "coal_kg")
        return coal_mass * self.co2_per_kg_coal

    def calculate_coal_for_co2_demand(self, co2_demand_kg: Any) -> float:
        """Return coal mass (kg) required to produce a target CO₂ quantity."""
        co2_mass = self._validate_mass(co2_demand_kg, "co2_demand_kg")
        if self.co2_per_kg_coal <= 0:
            raise ValueError("co2_per_kg_coal must be positive to compute demand.")
        return co2_mass / self.co2_per_kg_coal

    def calculate_coal_purchase_cost(self, coal_kg: Any) -> float:
        """Return the direct purchase cost (yuan) for the specified coal mass."""
        coal_mass = self._validate_mass(coal_kg, "coal_kg")
        return coal_mass * self.coal_price_yuan_per_kg

    def calculate_gasification_energy_cost(self, coal_kg: Any) -> float:
        """Return the energy cost (yuan) for gasifying the specified coal mass."""
        coal_mass = self._validate_mass(coal_kg, "coal_kg")
        return (
            coal_mass
            * self.gasification_energy_mj_per_kg
            * self.gasification_energy_cost_yuan_per_mj
        )

    def calculate_total_coal_cost(self, coal_kg: Any) -> CoalCostBreakdown:
        """
        Return the combined purchase and gasification energy costs for coal.

        The result includes the individual components and the summed value via
        the ``total_cost`` property.
        """
        purchase = self.calculate_coal_purchase_cost(coal_kg)
        gasification = self.calculate_gasification_energy_cost(coal_kg)
        return CoalCostBreakdown(purchase_cost=purchase, gasification_cost=gasification)

    def calculate_cost_per_kg_saf(
        self, coal_consumption_kg_per_kg_saf: Optional[float] = None
    ) -> CoalCostBreakdown:
        """
        Compute cost contributions per kilogram of SAF produced.

        Parameters
        ----------
        coal_consumption_kg_per_kg_saf:
            If provided, overrides the default coal consumption ratio loaded from
            configuration.
        """
        ratio = (
            self._validate_mass(coal_consumption_kg_per_kg_saf, "coal_consumption")
            if coal_consumption_kg_per_kg_saf is not None
            else self.coal_consumption_kg_per_kg_saf
        )
        if ratio <= 0:
            raise ValueError("Coal consumption ratio must be positive.")

        return self.calculate_total_coal_cost(ratio)

    def as_dict(self) -> Dict[str, Any]:
        """Expose the loaded parameters, useful for serialization or logging."""
        return {
            "coal_type": self.coal_type,
            "carbon_content": self.carbon_content,
            "co2_per_kg_coal": self.co2_per_kg_coal,
            "coal_price_yuan_per_ton": self.coal_price_yuan_per_ton,
            "coal_price_yuan_per_kg": self.coal_price_yuan_per_kg,
            "gasification_efficiency": self.gasification_efficiency,
            "gasification_energy_mj_per_kg": self.gasification_energy_mj_per_kg,
            "gasification_energy_cost_yuan_per_mj": self.gasification_energy_cost_yuan_per_mj,
            "coal_consumption_kg_per_kg_saf": self.coal_consumption_kg_per_kg_saf,
            "base_co2_yield_kg_per_kg_saf": self.base_co2_yield_kg_per_kg_saf,
        }
